In [1]:
import numpy as np
arr =np.arange(0, 4*2*4)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [2]:
v = arr.reshape([4,2,4])
v

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [3]:
v.sum()

496

In [4]:
res00 = v.sum(axis=0)
res00.shape

(2, 4)

In [5]:
res00

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [6]:
res01 = v.sum(axis=1)
res01.shape

(4, 4)

In [7]:
res01

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42],
       [52, 54, 56, 58]])

In [8]:
res02 = v.sum(axis=2)
res02.shape

(4, 2)

In [9]:
res02

array([[  6,  22],
       [ 38,  54],
       [ 70,  86],
       [102, 118]])